parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     miab
    database_user:     miab
    database_password: miab

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
    facebook_app_id:          524200894267634
    facebook_app_secret:      3a7390ccb847a47c15bc48a76055b6cb

