fos_facebook:
    alias:  facebook
    app_id: %facebook_app_id%
    secret: %facebook_app_secret%
    cookie: true
    permissions: [email]

fos_user:
    db_driver:          orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name:      public
    user_class:         Koala\UserBundle\Entity\User
    from_email:
        address:        me@example.com
        sender_name:    Example
    registration:
        confirmation:
            enabled:    true
